### PR TITLE
Added extension method ToDataTable() for converting ExcelWorksheet object to DataTable. In method ToDataSet, this method gets called to convert each sheet in the ExcelPackage object.

### PR DESCRIPTION
**Pull request by forandoe**
…ject to DataTable. Used this in the ToDataSet method. Users can now convert individual sheets to a DataTable. Also updated EPPlus nuget package.

### CODE REVIEW

**Comment by mikecole** [comment]
Hi, thanks for the pull request.

I've just added a test project. Can you please update your repo and add some tests for your pull request?

Sorry for adding those tests on you after the fact. I never expected any pull requests for this repo and now that I'm getting some I figured I'd better add tests.

**Comment by faredoon** [comment]
Hey Mike, no problem. I will get back after adding some tests. Thanks for the message.

**Comment by mikecole** [comment]
Hey @faredoon, I see there's branch conflicts between our branches that will need to be resolved before I can accept the pull request. Thanks!

**Comment by faredoon** [comment]
Hi Mike, you can probably ignore this pull request. I am in the process of adding test cases and will create a new pull request.

**Pull request closed without merging**
